

[[redirects]]
  from = "/about-me"
  to = "/about"
  status = 301
  force = true

[[redirects]]
  from = "/about-us"
  to = "/about"
  status = 301
  force = true

[[redirects]]
  from = "/contact-me"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/contact-us"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/privacy"
  to = "/privacy-policy"
  status = 301
  force = true

[[redirects]]
  from = "/projects/obsidian-astro-composer"
  to = "/projects/astro-composer"
  status = 301
  force = true

[[redirects]]
  from = "/docs/api-reference"
  to = "/docs/api"
  status = 301
  force = true

[[redirects]]
  from = "/docs/astro-modular-configuration"
  to = "/docs/configuration"
  status = 301
  force = true

[[redirects]]
  from = "/docs/sourcetree-and-git"
  to = "/docs/sourcetree-and-git-setup"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404